version: '3.8'
services:
  bdmongo:
    container_name: bdmongo
    restart: always
    image: mongo
    ports:
      - 29017:27017
    volumes:
      - './data/db:/data/db'
      - './data/confidb:/data/confidb'
  futsal-backend:
    container_name: futsal-server
    image: lowa/futsal-backend:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - NODE_ENV=desarrollo
      - DATABASE=mongodb://bdmongo:29017/FutsalDB
      - TOKEN_SECRET=1a2ffe36502bc61066c571867b7f458c
      - HOST_EMAIL_SISTEMA=c1470936.ferozo.com
      - EMAIL_SISTEMA=no-reply@elshowdelfutsal.com
      - PASS_EMAIL_SISTEMA=B4F2K3@NPY
      - PORT_EMAIL_SISTEMA=465
    volumes:
      - './public/imagenes/:/app/public/imagenes/'
    depends_on:
      - bdmongo
