import {keySubcategoria} from './enumeradores';

const listadoEquipos = [
  {
    id: 'aberastainsanlorenzo',
    nombreClub: 'aberastainsanlorenzo',
    escudo: 'aberastainsanlorenzo.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'accj',
    nombreClub: 'accj',
    escudo: 'accj.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'alianza',
    nombreClub: 'alianza',
    escudo: 'alianza.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'andacollo',
    nombreClub: 'andacollo',
    escudo: 'andacollo.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'area2',
    nombreClub: 'area2',
    escudo: 'area2.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'barriocgt',
    nombreClub: 'barriocgt',
    escudo: 'barriocgt.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'barrioescobar',
    nombreClub: 'barrioescobar',
    escudo: 'barrioescobar.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'barriolicciardi',
    nombreClub: 'barriolicciardi',
    escudo: 'barriolicciardi.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'barriomanantial',
    nombreClub: 'barriomanantial',
    escudo: 'barriomanantial.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'barriomercedario',
    nombreClub: 'barriomercedario',
    escudo: 'barriomercedario.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'barriopampa',
    nombreClub: 'barriopampa',
    escudo: 'barriopampa.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'barriorivadavia',
    nombreClub: 'barriorivadavia',
    escudo: 'barriorivadavia.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'barriosdepie',
    nombreClub: 'barriosdepie',
    escudo: 'barriosdepie.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'barriosolares',
    nombreClub: 'barriosolares',
    escudo: 'barriosolares.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'batistella',
    nombreClub: 'batistella',
    escudo: 'batistella.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'belgrano',
    nombreClub: 'belgrano',
    escudo: 'belgrano.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'benavidez',
    nombreClub: 'benavidez',
    escudo: 'benavidez.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'bermejito',
    nombreClub: 'bermejito',
    escudo: 'bermejito.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'bohemios',
    nombreClub: 'bohemios',
    escudo: 'bohemios.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'calise',
    nombreClub: 'calise',
    escudo: 'calise.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'centroimpulso',
    nombreClub: 'centroimpulso',
    escudo: 'centroimpulso.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'clubrivera',
    nombreClub: 'clubrivera',
    escudo: 'clubrivera.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'colon',
    nombreClub: 'colon',
    escudo: 'colon.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'comunicaciones',
    nombreClub: 'comunicaciones',
    escudo: 'comunicaciones.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'cooperativacaucete',
    nombreClub: 'cooperativacaucete',
    escudo: 'cooperativacaucete.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'cora',
    nombreClub: 'cora',
    escudo: 'cora.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'cuestadelviento',
    nombreClub: 'cuestadelviento',
    escudo: 'cuestadelviento.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    id: 'defensoresdeargentinos',
    nombreClub: 'defensoresdeargentinos',
    escudo: 'defensoresdeargentinos.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'defensoresdeleste',
    nombreClub: 'defensoresdeleste',
    escudo: 'defensoresdeleste.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'defensoreslosandes',
    nombreClub: 'defensoreslosandes',
    escudo: 'defensoreslosandes.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'delbono',
    nombreClub: 'delbono',
    escudo: 'delbono.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'dellibano',
    nombreClub: 'dellibano',
    escudo: 'dellibano.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'deportivochimbas',
    nombreClub: 'deportivochimbas',
    escudo: 'deportivochimbas.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    id: 'deportivosanjuan',
    nombreClub: 'deportivosanjuan',
    escudo: 'deportivosanjuan.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'donbosco',
    nombreClub: 'donbosco',
    escudo: 'donbosco.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'elglobo',
    nombreClub: 'elglobo',
    escudo: 'elglobo.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'escuelamunicipal25demayo',
    nombreClub: 'escuelamunicipal25demayo',
    escudo: 'escuelamunicipal25demayo.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'estrellajunior',
    nombreClub: 'estrellajunior',
    escudo: 'estrellajunior.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    id: 'federicomaggio',
    nombreClub: 'federicomaggio',
    escudo: 'federicomaggio.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'fundacionmiguelsanchez',
    nombreClub: 'fundacionmiguelsanchez',
    escudo: 'fundacionmiguelsanchez.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'hualilan',
    nombreClub: 'hualilan',
    escudo: 'hualilan.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'huarpes',
    nombreClub: 'huarpes',
    escudo: 'huarpes.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'independencia',
    nombreClub: 'independencia',
    escudo: 'independencia.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'juveniluta',
    nombreClub: 'juveniluta',
    escudo: 'juveniluta.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    id: 'juventuddelnorte',
    nombreClub: 'juventuddelnorte',
    escudo: 'juventuddelnorte.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'krause',
    nombreClub: 'krause',
    escudo: 'krause.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'lacolombia',
    nombreClub: 'lacolombia',
    escudo: 'lacolombia.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'lagloria',
    nombreClub: 'lagloria',
    escudo: 'lagloria.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'laprida',
    nombreClub: 'laprida',
    escudo: 'laprida.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'lasaguilas',
    nombreClub: 'lasaguilas',
    escudo: 'lasaguilas.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'lasgurkas',
    nombreClub: 'lasgurkas',
    escudo: 'lasgurkas.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'losalamos',
    nombreClub: 'losalamos',
    escudo: 'losalamos.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'losolivos',
    nombreClub: 'losolivos',
    escudo: 'losolivos.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'luzyfuerza',
    nombreClub: 'luzyfuerza',
    escudo: 'luzyfuerza.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'palermo',
    nombreClub: 'palermo',
    escudo: 'palermo.png',
    keySubcategoria: [keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'peñaflor',
    nombreClub: 'peñaflor',
    escudo: 'peñaflor.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    id: 'pumas',
    nombreClub: 'pumas',
    escudo: 'pumas.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'rivadavia',
    nombreClub: 'rivadavia',
    escudo: 'rivadavia.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'ruta20',
    nombreClub: 'ruta20',
    escudo: 'ruta20.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'sanciro',
    nombreClub: 'sanciro',
    escudo: 'sanciro.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'sanricardo',
    nombreClub: 'sanricardo',
    escudo: 'sanricardo.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'santodomingo',
    nombreClub: 'santodomingo',
    escudo: 'santodomingo.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'sargentocabral',
    nombreClub: 'sargentocabral',
    escudo: 'sargentocabral.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    id: 'sarmiento',
    nombreClub: 'sarmiento',
    escudo: 'sarmiento.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'simplemente',
    nombreClub: 'simplemente',
    escudo: 'simplemente.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'sindicatoempleadosdecomercio',
    nombreClub: 'sindicatoempleadosdecomercio',
    escudo: 'sindicatoempleadosdecomercio.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'spdesamparados',
    nombreClub: 'spdesamparados',
    escudo: 'spdesamparados.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'sportivo25demayo',
    nombreClub: 'sportivo25demayo',
    escudo: 'sportivo25demayo.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'tango',
    nombreClub: 'tango',
    escudo: 'tango.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    id: 'trinidad',
    nombreClub: 'trinidad',
    escudo: 'trinidad.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'ullum',
    nombreClub: 'ullum',
    escudo: 'ullum.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'union',
    nombreClub: 'union',
    escudo: 'union.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'uniondeportivocaucete',
    nombreClub: 'uniondeportivocaucete',
    escudo: 'uniondeportivocaucete.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    id: 'uvdonbosco',
    nombreClub: 'uvdonbosco',
    escudo: 'uvdonbosco.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    id: 'uvsanpatricio',
    nombreClub: 'uvsanpatricio',
    escudo: 'uvsanpatricio.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    id: 'villahipodromo',
    nombreClub: 'villahipodromo',
    escudo: 'villahipodromo.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    id: 'villaporres',
    nombreClub: 'villaporres',
    escudo: 'villaporres.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
];

export default listadoEquipos;
