import {keySubcategoria} from './enumeradores';

const listadoEquipos = [
  {
    _id: 'aberastainsanlorenzo',
    nombreClub: 'Aberastain San Lorenzo',
    escudo: 'aberastainsanlorenzo.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'accj',
    nombreClub: 'ACCJ',
    escudo: 'accj.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'alianza',
    nombreClub: 'Alianza',
    escudo: 'alianza.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'andacollo',
    nombreClub: 'Andacollo',
    escudo: 'andacollo.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'area2',
    nombreClub: 'Area II',
    escudo: 'area2.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'barriocgt',
    nombreClub: 'Barrio CGT',
    escudo: 'barriocgt.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'barrioescobar',
    nombreClub: 'Barrio Escobar',
    escudo: 'barrioescobar.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'barriolicciardi',
    nombreClub: 'Barrio Licciardi',
    escudo: 'barriolicciardi.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'barriomanantial',
    nombreClub: 'Barrio Manantial',
    escudo: 'barriomanantial.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'barriomercedario',
    nombreClub: 'Barrio Mercedario',
    escudo: 'barriomercedario.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'barriopampa',
    nombreClub: 'Barrio Pampa',
    escudo: 'barriopampa.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'barriorivadavia',
    nombreClub: 'Barrio Rivadavia',
    escudo: 'barriorivadavia.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'barriosdepie',
    nombreClub: 'Barrios de Pie',
    escudo: 'barriosdepie.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'barriosolares',
    nombreClub: 'Barrio Solares',
    escudo: 'barriosolares.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'batistella',
    nombreClub: 'Batistella',
    escudo: 'batistella.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'belgrano',
    nombreClub: 'Belgrano',
    escudo: 'belgrano.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'benavidez',
    nombreClub: 'Benavidez',
    escudo: 'benavidez.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'bermejito',
    nombreClub: 'Bermejito',
    escudo: 'bermejito.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'bohemios',
    nombreClub: 'Bohemios',
    escudo: 'bohemios.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'calise',
    nombreClub: 'Calise',
    escudo: 'calise.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'centroimpulso',
    nombreClub: 'Centro Impulso',
    escudo: 'centroimpulso.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'clubrivera',
    nombreClub: 'Club Rivera',
    escudo: 'clubrivera.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'colon',
    nombreClub: 'Colon',
    escudo: 'colon.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'comunicaciones',
    nombreClub: 'Comunicaciones',
    escudo: 'comunicaciones.png',
    keySubcategoria: [keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'cooperativacaucete',
    nombreClub: 'Cooperativa Caucete',
    escudo: 'cooperativacaucete.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'cora',
    nombreClub: 'CORA',
    escudo: 'cora.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'cuestadelviento',
    nombreClub: 'Cuesta del Viento',
    escudo: 'cuestadelviento.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    _id: 'defensoresdeargentinos',
    nombreClub: 'Defensores de Argentinos',
    escudo: 'defensoresdeargentinos.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'defensoresdeleste',
    nombreClub: 'Defensores del Este',
    escudo: 'defensoresdeleste.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'defensoreslosandes',
    nombreClub: 'Defensores Los Andes',
    escudo: 'defensoreslosandes.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'delbono',
    nombreClub: 'Del Bono',
    escudo: 'delbono.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'dellibano',
    nombreClub: 'Del Libano',
    escudo: 'dellibano.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'deportivochimbas',
    nombreClub: 'Deportivo Chimbas',
    escudo: 'deportivochimbas.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    _id: 'deportivosanjuan',
    nombreClub: 'Deportivo San Juan',
    escudo: 'deportivosanjuan.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'donbosco',
    nombreClub: 'Don Bosco',
    escudo: 'donbosco.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'elglobo',
    nombreClub: 'El Globo',
    escudo: 'elglobo.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'escuelamunicipal25demayo',
    nombreClub: 'Escuela Municipal 25 de Mayo',
    escudo: 'escuelamunicipal25demayo.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'estrellajunior',
    nombreClub: 'Estrella Junior',
    escudo: 'estrellajunior.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    _id: 'federicomaggio',
    nombreClub: 'Federico Maggio',
    escudo: 'federicomaggio.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'fundacionmiguelsanchez',
    nombreClub: 'Fundacion Miguel Sanchez',
    escudo: 'fundacionmiguelsanchez.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'hualilan',
    nombreClub: 'Hualilan',
    escudo: 'hualilan.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'huarpes',
    nombreClub: 'Huarpes',
    escudo: 'huarpes.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'independencia',
    nombreClub: 'Independencia',
    escudo: 'independencia.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'juveniluta',
    nombreClub: 'Juvenil UTA',
    escudo: 'juveniluta.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    _id: 'juventuddelnorte',
    nombreClub: 'Juventud del Norte',
    escudo: 'juventuddelnorte.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'krause',
    nombreClub: 'Krause',
    escudo: 'krause.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'lacolombia',
    nombreClub: 'La Colombia',
    escudo: 'lacolombia.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'lagloria',
    nombreClub: 'La Gloria',
    escudo: 'lagloria.png',
    keySubcategoria: [keySubcategoria.Masc_divA, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'laprida',
    nombreClub: 'Laprida',
    escudo: 'laprida.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'lasaguilas',
    nombreClub: 'Las Aguilas',
    escudo: 'lasaguilas.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'lasgurkas',
    nombreClub: 'Las Gurkas',
    escudo: 'lasgurkas.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'losalamos',
    nombreClub: 'Los Alamos',
    escudo: 'losalamos.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'losolivos',
    nombreClub: 'Los Olivos',
    escudo: 'losolivos.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'luzyfuerza',
    nombreClub: 'Luz y Fuerza',
    escudo: 'luzyfuerza.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'palermo',
    nombreClub: 'Palermo',
    escudo: 'palermo.png',
    keySubcategoria: [keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'peñaflor',
    nombreClub: 'Peñaflor',
    escudo: 'peñaflor.png',
    keySubcategoria: [keySubcategoria.Masc_divC],
    idSubcategorias: [keySubcategoria.Masc_divC.toString()],
  },
  {
    _id: 'pumas',
    nombreClub: 'Pumas',
    escudo: 'pumas.png',
    keySubcategoria: [keySubcategoria.Masc_divD, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divD.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'rivadavia',
    nombreClub: 'Rivadavia',
    escudo: 'rivadavia.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'ruta20',
    nombreClub: 'Ruta 20',
    escudo: 'ruta20.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'sanciro',
    nombreClub: 'San Ciro',
    escudo: 'sanciro.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'sanricardo',
    nombreClub: 'San Ricardo',
    escudo: 'sanricardo.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'santodomingo',
    nombreClub: 'Santo Domingo',
    escudo: 'santodomingo.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'sargentocabral',
    nombreClub: 'Sargento Cabral',
    escudo: 'sargentocabral.png',
    keySubcategoria: [keySubcategoria.Masc_divB],
    idSubcategorias: [keySubcategoria.Masc_divB.toString()],
  },
  {
    _id: 'sarmiento',
    nombreClub: 'Sarmiento',
    escudo: 'sarmiento.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'simplemente',
    nombreClub: 'Simplemente',
    escudo: 'simplemente.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'sindicatoempleadosdecomercio',
    nombreClub: 'SEC',
    escudo: 'sindicatoempleadosdecomercio.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'spdesamparados',
    nombreClub: 'Sportivo Desamparados',
    escudo: 'spdesamparados.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'sportivo25demayo',
    nombreClub: 'Sportivo 25 de Mayo',
    escudo: 'sportivo25demayo.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'tango',
    nombreClub: 'Tango',
    escudo: 'tango.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divB],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divB.toString()],
  },
  {
    _id: 'trinidad',
    nombreClub: 'Trinidad',
    escudo: 'trinidad.png',
    keySubcategoria: [keySubcategoria.Masc_divC, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divC.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'ullum',
    nombreClub: 'Ullum',
    escudo: 'ullum.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'union',
    nombreClub: 'Union',
    escudo: 'union.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'uniondeportivocaucete',
    nombreClub: 'Union Deportivo Caucete',
    escudo: 'uniondeportivocaucete.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
  {
    _id: 'uvdonbosco',
    nombreClub: 'UV Don Bosco',
    escudo: 'uvdonbosco.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    _id: 'uvsanpatricio',
    nombreClub: 'UV San Patricio',
    escudo: 'uvsanpatricio.png',
    keySubcategoria: [keySubcategoria.Masc_divD],
    idSubcategorias: [keySubcategoria.Masc_divD.toString()],
  },
  {
    _id: 'villahipodromo',
    nombreClub: 'Villa Hipodromo',
    escudo: 'villahipodromo.png',
    keySubcategoria: [keySubcategoria.Masc_divB, keySubcategoria.Fem_divA],
    idSubcategorias: [keySubcategoria.Masc_divB.toString(), keySubcategoria.Fem_divA.toString()],
  },
  {
    _id: 'villaporres',
    nombreClub: 'Villa Porres',
    escudo: 'villaporres.png',
    keySubcategoria: [keySubcategoria.Masc_divA],
    idSubcategorias: [keySubcategoria.Masc_divA.toString()],
  },
];

export default listadoEquipos;
