const listadoNoticias = [
  {
    _id: 'ARRANCA_UNA_NUEVA_ETAPA_LOS_FINES_DE_SEMANA_1645506917255',
    fecha: '2022-01-21T11:57:02.744Z',
    titulo: 'ARRANCA UNA NUEVA ETAPA LOS FINES DE SEMANA',
    copete:
      'Por primera vez en la historia el la Divisional A disputará sus encuentros sábados y domingos. La Gloria, el actual campeón, buscará retener el título. ',
    idEtiquetas: [],
    keyCategoria: 1,
    keySubcategoria: 1,
    isDestacada: false,
    idImagen: ['VX-edUdLyRB-S8Sh8VxT0JBj.jpg'],
    idCategoria: '1',
    idSubcategoria: '1',
  },
  {
    _id: 'UNA_VEZ_MÁS_SUSPENDIDA_LA_DIVISIONAL_A_1645506917255',
    fecha: '2022-01-21T12:12:24.119Z',
    titulo: 'UNA VEZ MÁS SUSPENDIDA LA DIVISIONAL A',
    copete:
      'Luego de algunos problemas con los árbitros, la Comisión Directiva del Futsal sanjuanino suspendió hasta nuevo aviso la categoría. ',
    idEtiquetas: [],
    keyCategoria: 1,
    keySubcategoria: 1,
    isDestacada: false,
    idImagen: ['KnZuKiQTN4QDqvqp5pY0vnHu.jpg'],
    idCategoria: '1',
    idSubcategoria: '1',
  },
  {
    _id: 'PUMAS_Y_BERMEJITO_A_LA_CABEZA_1645506917255',
    fecha: '2022-01-21T12:15:19.950Z',
    titulo: 'PUMAS Y BERMEJITO A LA CABEZA',
    copete:
      'Los dos equipos lograron puntaje ideal luego de tres fechas transcurridas. El último campeón, Estrella Jrs., empató ante Deportivo Chimbas. ',
    idEtiquetas: [],
    keyCategoria: 1,
    keySubcategoria: 4,
    isDestacada: false,
    idImagen: ['FHbYU73_CwGutWqIxDi34Ceo.jpg'],
    idCategoria: '1',
    idSubcategoria: '4',
  },
  {
    _id: 'MERCEDARIO_Y_DESAMPARADOS_LOS_ASCENDIDOS_A_LA_B_1645506917255',
    fecha: '2022-01-21T12:19:05.454Z',
    titulo: 'MERCEDARIO Y DESAMPARADOS LOS ASCENDIDOS A LA B',
    copete:
      'Los dos equipos serán parte de la segunda categoría del futsal sanjuanino luego de una gran temporada 2021.  ',
    idEtiquetas: [],
    keyCategoria: 1,
    keySubcategoria: 3,
    isDestacada: false,
    idImagen: ['3ZFyIx2P6OLFABBfZA1OhEyZ.jpeg'],
    idCategoria: '1',
    idSubcategoria: '3',
  },
  {
    _id: 'LAS_GLORIOSAS_BUSCAN_FUTURO_A_LARGO_PLAZO_1645506917255',
    fecha: '2022-01-21T12:22:46.862Z',
    titulo: 'LAS GLORIOSAS BUSCAN FUTURO A LARGO PLAZO',
    copete:
      'La institución gloriosa será una de los pocos equipos que contará con divisiones inferiores femenina. La idea es tener una etapa formativa dentro de las chicas.',
    idEtiquetas: [],
    keyCategoria: 4,
    keySubcategoria: 12,
    isDestacada: false,
    idImagen: ['c8YAv0CPQfNbmpkxViFKdJU3.jpeg'],
    idCategoria: '4',
    idSubcategoria: '12',
  },
  {
    _id: 'RAWSON_CONSTRUYE_FUTURO_EN_EL_FUTSAL_1645506917255',
    fecha: '2022-01-21T12:24:34.950Z',
    titulo: 'RAWSON CONSTRUYE FUTURO EN EL FUTSAL',
    copete:
      'El departamento con más cantidad de jugadores en la provincia apuesta por las bases. Con un grupo interdisciplinario de trabajo buscan generar herramientas en las promesas del futsal, a futuro. ',
    idEtiquetas: [],
    keyCategoria: 4,
    keySubcategoria: 12,
    isDestacada: true,
    idImagen: ['uCahjAt03wKWc8_TcEtHB2UJ.jpeg'],
    idCategoria: '4',
    idSubcategoria: '12',
  },
  {
    _id: 'PODIO_COMPLETO_PARA_LA_SELECCIÓN_DE_RAWSON_EN_LA_FELIZ_1645506917255',
    fecha: '2022-01-21T12:28:17.374Z',
    titulo: 'PODIO COMPLETO PARA LA SELECCIÓN DE RAWSON EN LA FELIZ',
    copete:
      'La Selección de Rawson logró un 1er, un 2do y un 3er puesto en la primera edición de la “Mar del Plata Futsal Cup”. Además se finalizó 4to en la categoría sub 16. ',
    idEtiquetas: [],
    keyCategoria: 4,
    keySubcategoria: 12,
    isDestacada: false,
    idImagen: ['cLn-spBcAfPhN-KmMWSa4xLQ.jpeg'],
    idCategoria: '4',
    idSubcategoria: '12',
  },
  {
    _id: 'SAN_JUAN_TENDRÁ_CUATRO_SANJUANINOS_EN_RÍO_CUARTO_1645506917255',
    fecha: '2022-01-21T12:30:26.373Z',
    titulo: 'SAN JUAN TENDRÁ CUATRO SANJUANINOS EN RÍO CUARTO',
    copete:
      'La Gloria, Huarpes, Punta del Médano y A.M.F.A buscarán quedarse con dos de los pasajes para la Fase Final de la Liga Nacional de Futsal.',
    idEtiquetas: [],
    keyCategoria: 3,
    keySubcategoria: 10,
    isDestacada: true,
    idImagen: ['Y4bQ-Qot0sL33y__oulaDuqi.jpg'],
    idCategoria: '3',
    idSubcategoria: '10',
  },
  {
    _id: 'EL_ARBITRAJE_SANJUANINO_ESTARÁ_PRESENTE_EN_EL_REGIONAL_1645506917255',
    fecha: '2022-01-21T12:31:40.591Z',
    titulo: 'EL ARBITRAJE SANJUANINO ESTARÁ PRESENTE EN EL REGIONAL',
    copete:
      'Como en las dos últimas ediciones la provincia contará con dos jueces que serán parte de los encuentros de la Fase Cuyo.',
    idEtiquetas: [],
    keyCategoria: 3,
    keySubcategoria: 10,
    isDestacada: true,
    idImagen: ['h-Sv4sg7XDo5_bAGn6vDuBlP'],
    idCategoria: '3',
    idSubcategoria: '10',
  },
  {
    _id: 'ESTE_MIÉRCOLES_ARRANCA_LA_FASE_FINAL_DE_LA_LIGA_NACIONAL_1645506917255',
    fecha: '2022-01-25T11:37:38.104Z',
    titulo: 'ESTE MIÉRCOLES ARRANCA LA FASE FINAL DE LA LIGA NACIONAL',
    copete:
      'Con la presencia de Huarpes y La Gloria, la provincia de San Juan recibirá el mejor futsal de la Argentina. El plato fuerte de la 1er fecha será Huarpes-Barracas. ',
    idEtiquetas: [],
    keyCategoria: 3,
    keySubcategoria: 11,
    isDestacada: true,
    idImagen: ['Bph3ToPttw8s26T_1kghe6r7.jpeg'],
    idCategoria: '3',
    idSubcategoria: '11',
  },
  {
    _id: 'DESAMPARADOS_SIGUE_DANDO_QUE_HABLAR_EN_LA_B_1645506917255',
    fecha: '2022-01-21T12:35:50.390Z',
    titulo: 'DESAMPARADOS SIGUE DANDO QUE HABLAR EN LA B',
    copete:
      'Las víboras consiguieron su cuarta victoria al hilo y sigue como único líder de la zona B. El otro con puntaje ideal es Coop. Caucete.',
    idEtiquetas: [],
    keyCategoria: 2,
    keySubcategoria: 7,
    isDestacada: false,
    idImagen: ['BM_IypUDtgJgY9cmnMpC709r'],
    idCategoria: '2',
    idSubcategoria: '7',
  },
  {
    _id: 'A_LA_ESPERA_DEL_ÚLTIMO_ASCENSO__1645506917255',
    fecha: '2022-01-21T12:37:15.117Z',
    titulo: 'A LA ESPERA DEL ÚLTIMO ASCENSO ',
    copete:
      'Cinco equipos tienen su lugar en la máxima categoría del futsal femenino. Todavía resta definirse el sexto equipo que formará parte de la temporada 2022.',
    idEtiquetas: [],
    keyCategoria: 2,
    keySubcategoria: 7,
    isDestacada: false,
    idImagen: ['p7RBbNoCLYfnBC2G5cNtfKoZ.jpeg'],
    idCategoria: '2',
    idSubcategoria: '7',
  },
  {
    _id: 'RIVERA_GRITA_FUERTE,_TRICAMPEÓN_1645506917255',
    fecha: '2022-01-21T12:38:45.101Z',
    titulo: 'RIVERA GRITA FUERTE, TRICAMPEÓN',
    copete:
      'El elenco de Chimbas se consagró como el mejor equipo del año 2021, luego de ganar el Apertura y Clausura. Esta vez Palermo se tuvo que conformar con el 2do puesto. ',
    idEtiquetas: [],
    keyCategoria: 2,
    keySubcategoria: 6,
    isDestacada: true,
    idImagen: ['LPgn9s8vcEDlJZX33FqnClSd.jpeg'],
    idCategoria: '2',
    idSubcategoria: '6',
  },
  {
    _id: 'TORNEO_PROVINCIAL_FEMENINO_EN_CALINGASTA_1645506917255',
    fecha: '2022-01-22T10:16:52.146Z',
    titulo: 'TORNEO PROVINCIAL FEMENINO EN CALINGASTA',
    copete:
      'La rama femenina buscará a sus dos representantes para la Liga Nacional Femenina de Futsal, en esta oportunidad 3 Ligas de la provincia tendrán sus representantes. ',
    idEtiquetas: [],
    keyCategoria: 2,
    keySubcategoria: 6,
    isDestacada: true,
    idImagen: ['-mJU9LyqexMcfjLXPMN9-SG1.jpeg'],
    idCategoria: '2',
    idSubcategoria: '6',
  },
  {
    _id: 'LA_GLORIA_Y_HUARPES_SE_VAN_PARA_EL_REGIONAL_1645506917255',
    fecha: '2022-01-21T18:14:25.347Z',
    titulo: 'LA GLORIA Y HUARPES SE VAN PARA EL REGIONAL',
    copete:
      'Luego de 5 fechas cambiantes, donde la punta tuvo varios dueños, los gloriosos y caciques volverán a ir a la Fase Regional de la Liga Nacional como en el 2018.',
    idEtiquetas: [],
    keyCategoria: 3,
    keySubcategoria: 9,
    isDestacada: false,
    idImagen: ['pHTES5mkqMy_k2qtCIhekP3U.jpg'],
    idCategoria: '3',
    idSubcategoria: '9',
  },
  {
    _id: 'CONSORCIO_EL_NUEVO_CAMPEÓN_DE_CALINGASTA_1645506917255',
    fecha: '2022-01-21T20:46:02.052Z',
    titulo: 'CONSORCIO EL NUEVO CAMPEÓN DE CALINGASTA',
    copete:
      'En una gran final los nuevos monarcas derrotaron a quien era el campeón reinante AMFA, de esta manera suma su primer estrella',
    idEtiquetas: [],
    keyCategoria: 4,
    keySubcategoria: 13,
    isDestacada: false,
    idImagen: ['LHukeBgS_0rfARN30peZ3-3R.jpeg'],
    idCategoria: '4',
    idSubcategoria: '13',
  },
  {
    _id: 'RIVERA_Y_BARRIOS_DE_PIE_ARRANCARON_GOLEANDO_1645506917255',
    fecha: '2022-01-22T10:12:58.767Z',
    titulo: 'RIVERA Y BARRIOS DE PIE ARRANCARON GOLEANDO',
    copete:
      'Los equipos de la Capital empezaron con el pie derecho tras golear a Belgrano y AMFA respectivamente. Hoy se lleva a cabo el 2do cruce.',
    idEtiquetas: [],
    keyCategoria: 2,
    keySubcategoria: 6,
    isDestacada: false,
    idImagen: ['eHgLQu8_aMRzcxx_r3eTNaR-.jpeg'],
    idCategoria: '2',
    idSubcategoria: '6',
  },
  {
    _id: 'LA_GRN_FINAL:_RIVERA_-_B.D.P_SOLIRDARIDAD_1645506917255',
    fecha: '2022-01-23T14:29:18.890Z',
    titulo: 'LA GRN FINAL: RIVERA - B.D.P SOLIRDARIDAD',
    copete:
      'Como en el torneo doméstico los dos equipos se medirán por un lugar en el certamen regional. Será a las 18.30 en el Estadio de Barreal.',
    idEtiquetas: [],
    keyCategoria: 2,
    keySubcategoria: 6,
    isDestacada: true,
    idImagen: ['0iBcODBLyVcPa-QDUBr_0w28.jpeg'],
    idCategoria: '2',
    idSubcategoria: '6',
  },
  {
    _id: 'CHARLA_Y_ENTRENAMIENTO_DE_FUTSAL_EN_25_DE_MAYO_1645506917255',
    fecha: '2022-01-27T15:55:21.264Z',
    titulo: 'CHARLA Y ENTRENAMIENTO DE FUTSAL EN 25 DE MAYO',
    copete:
      'El Profesor Matías Illanes llevó a cabo una capacitación para chicos entre 12 y 16 años, con la finalidad de brindar herramientas para los jóvenes del departamento. La Escuela Municipal 25 de Mayo fue la encargada de la organización del evento. ',
    idEtiquetas: [],
    keyCategoria: 4,
    keySubcategoria: 12,
    isDestacada: true,
    idImagen: ['dmwh9J5v5l2f8uC_drrZ5cL_.jpeg'],
    idCategoria: '4',
    idSubcategoria: '12',
  },
  {
    _id: 'TORNEO_DE_VERANO_EN_LAPRIDA_1645506917255',
    fecha: '2022-01-28T09:12:46.612Z',
    titulo: 'TORNEO DE VERANO EN LAPRIDA',
    copete:
      'El certamen contará con la presencia de 8 equipos de categoría Sub 17, con el fin de darle rodaje a los más chicos.',
    idEtiquetas: [],
    keyCategoria: 4,
    keySubcategoria: 12,
    isDestacada: false,
    idImagen: ['SysIs3KVrwf_vw3kKR18cn2H.jpg'],
    idCategoria: '4',
    idSubcategoria: '12',
  },
  {
    _id: '¿Y_AHORA?__1645506917255',
    fecha: '2022-02-07T10:40:03.824Z',
    titulo: '¿Y AHORA? ',
    copete: 'El tribunal de faltas de la Liga Sanjuanina renunició y la actividad seguirá parada.',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '2',
    keyCategoria: 1,
    keySubcategoria: 2,
    isDestacada: false,
    idImagen: ['Ea27d7zw7BvNakiUL087E1d1.jpg'],
  },
  {
    _id: 'UN_JUGADOR_DE_CGT_TUVO_UN_ACCIDENTE_Y_CASI_PIERDE_LA_VIDA_1645506917256',
    fecha: '2022-02-07T10:52:48.886Z',
    titulo: 'UN JUGADOR DE CGT TUVO UN ACCIDENTE Y CASI PIERDE LA VIDA',
    copete:
      'Lucas Castro jugador de las inferiores del Barrio CGT fue atropellado y quedó en estado de inconsciencia. Ahora se encuentra fuera de peligro pero con una recuperación que llevará mucho tiempo',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '2',
    keyCategoria: 1,
    keySubcategoria: 2,
    isDestacada: false,
    idImagen: ['CEcgciEeZyWKRzseOgr8kWQ5.jpg'],
  },
  {
    _id: 'UN_BARRIO_SOLARES_QUIERE_EL_ASCENSO_A_PRIMERA_1645506917256',
    fecha: '2022-02-07T11:34:03.466Z',
    titulo: 'UN BARRIO SOLARES QUIERE EL ASCENSO A PRIMERA',
    copete:
      'Uno de los mejores equipos de la temporada 2021 intentará seguir su marcha triunfal para la primer categoría del futsal sanjuanino. ',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '2',
    keyCategoria: 1,
    keySubcategoria: 2,
    isDestacada: false,
    idImagen: ['db9gto4KDBUr3WFprGSzycFL.jpg'],
  },
  {
    _id: 'ARGENTINA_CAMPEÓN_DE_AMÉRICA__1645506917256',
    fecha: '2022-02-07T14:14:23.545Z',
    titulo: 'ARGENTINA CAMPEÓN DE AMÉRICA ',
    copete:
      'La Selección Argentina le ganó 1-0 a Paraguay en Asunción y se consagró campeón de América por tercera vez en su historia. El gol lo marcó Alan Brandi en el primer tiempo, donde la Albiceleste fue superior. En el complemento supo aguantar la ventaja y disimuló el desgaste físico de la semifinal ante Brasil.',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '15',
    keyCategoria: 4,
    keySubcategoria: 15,
    isDestacada: true,
    idImagen: ['evK91PthLh4WIrZu7VxYFDJ6.jpg'],
  },
  {
    _id: 'BRASIL_DECIME_QUE_SE_SIENTE!!!_1645506917256',
    fecha: '2022-02-07T14:20:03.640Z',
    titulo: 'BRASIL DECIME QUE SE SIENTE!!!',
    copete:
      'La Selección Argentina derrotó en los penales a Brasil con una estupenda actuación de Nicolás Sarmiento, luego de haber empatado 3-3 en el tiempo regular y jugará la final de la Copa América este domingo, a las 17, ante Paraguay.',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '15',
    keyCategoria: 4,
    keySubcategoria: 15,
    isDestacada: false,
    idImagen: ['U1t4hYpKQvfDOYcqrebT6hWR.jpg'],
  },
  {
    _id: 'EMPATE_CON_PARAGUAY,_Y_FINAL_CON_BRASIL__1645506917256',
    fecha: '2022-02-07T14:22:08.215Z',
    titulo: 'EMPATE CON PARAGUAY, Y FINAL CON BRASIL ',
    copete:
      'La Selección Argentina le ganó 1-0 a Paraguay en Asunción y se consagró campeón de América por tercera vez en su historia. El gol lo marcó Alan Brandi en el primer tiempo, donde la Albiceleste fue superior. En el complemento supo aguantar la ventaja y disimuló el desgaste físico de la semifinal ante Brasil.',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '15',
    keyCategoria: 4,
    keySubcategoria: 15,
    isDestacada: false,
    idImagen: ['FmXb4b1ogjxKg32Y-T0O5NVF.jpg'],
  },
  {
    _id: 'COPA_25_DE_MAYO__1645506917256',
    fecha: '2022-02-08T11:11:33.371Z',
    titulo: 'COPA 25 DE MAYO ',
    copete:
      'Veintidos equipos del departamento, Rawson. 9 de Julio y  Caucete disputan el certamen departamental con el fin de coronarse como el mejor del Este. ',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '14',
    keyCategoria: 4,
    keySubcategoria: 14,
    isDestacada: false,
    idImagen: ['PVaM5ARJ_ELrY1jRmaX-SXjA.jpg'],
  },
  {
    _id: 'TORNEO_INFANTO_JUVENIL_DE_FUTSAL_"GLORIA_SANJUANINA"_1645506917256',
    fecha: '2022-02-08T08:28:35.377Z',
    titulo: 'TORNEO INFANTO JUVENIL DE FUTSAL "GLORIA SANJUANINA"',
    copete:
      'Más de 200 chicos participaron del certamen que organizó el último campeón de la Divisional A del futsal sanjuanino. ',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '12',
    keyCategoria: 4,
    keySubcategoria: 12,
    isDestacada: false,
    idImagen: ['HHu5LLJW4X-Txr7rWsVtymm3.jpg'],
  },
  {
    _id: 'BARRACAS_EL_NUEVO_CAMPEÓN_DE_LA_LIGA_NACIONAL__1645506917256',
    fecha: '2022-02-08T11:59:16.526Z',
    titulo: 'BARRACAS EL NUEVO CAMPEÓN DE LA LIGA NACIONAL ',
    copete:
      'En la última jornada de competencia, el elenco Barraqueño se impuso ante Boca. Y en San Juan, el terruño de la Revolución Deportiva, se coronó como el mejor del torneo.',
    idEtiquetas: [],
    idCategoria: '3',
    idSubcategoria: '11',
    keyCategoria: 3,
    keySubcategoria: 11,
    isDestacada: false,
    idImagen: ['KxFfKM5YDHTOddSmbQNGn7dj.jpg'],
  },
  {
    _id: 'HUARPES_EL_MEJOR_SANJUANINO_1645506917256',
    fecha: '2022-02-08T12:03:29.452Z',
    titulo: 'HUARPES EL MEJOR SANJUANINO',
    copete:
      'El naranja se quedó con el 6to lugar tras perder con Banco Provincia de Mar del Plata. Mientras que La Gloria se quedó con el último lugar.',
    idEtiquetas: [],
    idCategoria: '3',
    idSubcategoria: '11',
    keyCategoria: 3,
    keySubcategoria: 11,
    isDestacada: false,
    idImagen: ['92LTaenxD5-j_sIZF3z-EJjg.jpg'],
  },
  {
    _id: 'ERNESTO_“TITO”_PEZE_NUEVO_TÉCNICO_DE_LAPRIDA_1645506917256',
    fecha: '2022-02-09T09:51:04.782Z',
    titulo: 'ERNESTO “TITO” PEZE NUEVO TÉCNICO DE LAPRIDA',
    copete:
      'El ex profesor y ayudante de campo del SEC tendrá una nueva experiencia en la Divisional D del futsal sanjuanino. ',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '4',
    keyCategoria: 1,
    keySubcategoria: 4,
    isDestacada: false,
    idImagen: ['n_2jWu3a-oPtiVV-IphyDGJm.jpeg'],
  },
  {
    _id: 'SE_VIENE_LA_COPA_POCITO__1645506917256',
    fecha: '2022-02-09T13:56:08.360Z',
    titulo: 'SE VIENE LA COPA POCITO ',
    copete:
      'El torneo puesta a punto se llevará a cabo en el complejo deportivo Laprida, con la participación de 20 equipos que se medirán a lo largo del certamen departamental.',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '14',
    keyCategoria: 4,
    keySubcategoria: 14,
    isDestacada: false,
    idImagen: ['Qtod_aae1eW12HBE7rFv3EeW.jpeg'],
  },
  {
    _id: 'ASÍ_COMIENZA_LA_COPA_POCITO__1645506917256',
    fecha: '2022-02-10T08:36:13.386Z',
    titulo: 'ASÍ COMIENZA LA COPA POCITO ',
    copete:
      'Se definieron los grupos que darán comienzo a la 2da edición del certamen departamental. A último momento se agregó F. Miguel Sanchez. ',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '14',
    keyCategoria: 4,
    keySubcategoria: 14,
    isDestacada: false,
    idImagen: ['RbTQ-UFmXvgn9yRK_N6vprhg.jpeg'],
  },
  {
    _id: '"SE_VIENE_UN_2022_CARGADO_Y_MUCHAS_EXPECTATIVAS"_1645506917256',
    fecha: '2022-02-10T12:38:59.769Z',
    titulo: '"SE VIENE UN 2022 CARGADO Y MUCHAS EXPECTATIVAS"',
    copete:
      'El DT de Barrio Rivadavia, Lucas Godoy, nos cuenta como se vienen preparando para esta nueva temporada y sobre su ascenso a la primer categoría.',
    idEtiquetas: [],
    idCategoria: '2',
    idSubcategoria: '7',
    keyCategoria: 2,
    keySubcategoria: 7,
    isDestacada: false,
    idImagen: ['GGULVMfWvjhvJbAKT7_TTssM.jpeg'],
  },
  {
    _id: 'BERMEJITO_SE_PREPARA_CON_TODO_PARA_EL_2022_1645506917256',
    fecha: '2022-02-10T12:55:58.390Z',
    titulo: 'BERMEJITO SE PREPARA CON TODO PARA EL 2022',
    copete:
      'El celeste sigue trabajando para una nueva temporada en el 2022 en la Divisional D del futsal masculino',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '4',
    keyCategoria: 1,
    keySubcategoria: 4,
    isDestacada: false,
    idImagen: ['HtaQeLFzgQNE0RcSQu5pivyL.jpeg'],
  },
  {
    _id: 'LAS_BERMEJITAS_BUSCARÁN_EL_NUEVO_ASCENSO_1645506917256',
    fecha: '2022-02-10T13:14:28.452Z',
    titulo: 'LAS BERMEJITAS BUSCARÁN EL NUEVO ASCENSO',
    copete:
      'Las celestitas tendrán un nuevo año en la segunda categoría del futsal femenino, en búsqueda de experiencia y ganas de triunfar',
    idEtiquetas: [],
    idCategoria: '2',
    idSubcategoria: '7',
    keyCategoria: 2,
    keySubcategoria: 7,
    isDestacada: false,
    idImagen: ['UNpmm0xxHUGPh93O8gInxGqV.jpeg'],
  },
  {
    _id: 'CAMPEONATO_FUTSAL_FEMENINO_CAUCETE_2022_1645506917256',
    fecha: '2022-02-11T09:40:20.432Z',
    titulo: 'CAMPEONATO FUTSAL FEMENINO CAUCETE 2022',
    copete: 'Este fin de semana se disputará la gran final entre Área II y F-100. ',
    idEtiquetas: [],
    idCategoria: '4',
    idSubcategoria: '13',
    keyCategoria: 4,
    keySubcategoria: 13,
    isDestacada: false,
    idImagen: ['GQ6I4-76rZPAuknpSVINxBxc.jpg'],
  },
  {
    _id: 'UN_EQUIPO_QUE_ASPIRA_AL_ASCENSO_DIRECTO_1645506917256',
    fecha: '2022-02-11T10:36:07.136Z',
    titulo: 'UN EQUIPO QUE ASPIRA AL ASCENSO DIRECTO',
    copete:
      'Pumas buscará demostrar porque fue uno de los mejores equipos del 2021, cerrando con el broche de oro: el ascenso a la C.',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '4',
    keyCategoria: 1,
    keySubcategoria: 4,
    isDestacada: false,
    idImagen: ['35Wpo_ZYbJrYrZgfOHdoktdI.jpg'],
  },
  {
    _id: 'EL_LECHUZO_VOLVIÓ_A_LOS_ENTRENAMIENTOS_CON_GRAN_CONVOCATORIA_1645506917256',
    fecha: '2022-02-11T11:16:58.231Z',
    titulo: 'EL LECHUZO VOLVIÓ A LOS ENTRENAMIENTOS CON GRAN CONVOCATORIA',
    copete:
      'Más de 40 jugadores conforman parte de los planteles de primera y reserva del equipo más ganador del futsal sanjuanino.',
    idEtiquetas: [],
    idCategoria: '1',
    idSubcategoria: '1',
    keyCategoria: 1,
    keySubcategoria: 1,
    isDestacada: false,
    idImagen: ['lGLxCJx5y9AqFdicJWGCL5mI.jpeg'],
  },
];

export default listadoNoticias;
